packages:
  - apps/*
  - packages/*

overrides:
  prismjs@<1.30.0: '>=1.30.0'
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  vite@>=7.0.0 <=7.0.6: '>=7.0.7'
  hono@<4.9.7: '>=4.9.7'
  vite@>=7.0.0 <=7.0.7: '>=7.0.8'
  hono@>=1.1.0 <4.10.2: '>=4.10.2'
  playwright@<1.55.1: '>=1.55.1'
  tar-fs@>=3.0.0 <3.1.1: '>=3.1.1'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  valibot@>=0.31.0 <1.2.0: '>=1.2.0'
  hono@<4.10.3: '>=4.10.3'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  langchain@<0.3.37: '>=0.3.37'
  '@langchain/core@<0.3.80': '>=0.3.80'
  qs@<6.14.1: '>=6.14.1'
