// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "metadata": {
    "title": "Phu Luong",
    "description": "Showcasing passion, experience, and projects — one byte at a time.",
    "about": {
      "title": "About Me",
      "description": "A journey through my background, education, and technical stack."
    },
    "experience": {
      "title": "Experience",
      "description": "A professional timeline of my roles and hands-on contributions."
    },
    "projects": {
      "title": "Projects",
      "description": "A collection of my work, from academic builds to real-world solutions."
    },
    "contact": {
      "title": "Contact",
      "description": "Let's connect for collaborations or professional inquiries."
    },
    "blogs": {
      "title": "Blog",
      "description": "Insights, tutorials, and reflections on technology and development."
    }
  },
  "global": {
    "tableOfContent": "Table of Content",
    "userToggle": {
      "signOut": "Sign out",
      "admin": "Admin",
      "viewer": "Viewer"
    },
    "i18nToggle": {
      "toggleLanguage": "Toggle language",
      "vietnamese": "Vietnamese",
      "english": "English",
      "french": "French"
    },
    "modeToggle": {
      "toggleTheme": "Toggle theme",
      "light": "Light",
      "dark": "Dark",
      "system": "System"
    },
    "search": {
      "searchProjects": "Search projects",
      "all": "All"
    },
    "header": {
      "skipToContent": "Skip to main content",
      "nav": {
        "home": "Home",
        "about": "About",
        "experience": "Experience",
        "projects": "Projects",
        "blogs": "Blogs",
        "hobbies": "Hobbies",
        "more": "More",
        "letsTalk": "Let's talk",
        "askMe": "Ask Me",
        "anythingAboutMe": "Anything about me",
        "cv": "CV"
      }
    },
    "footer": {
      "home": "Home",
      "builtBy": "Built by",
      "openSource": "Open source on",
      "links": "Quick Links",
      "about": "About",
      "projects": "Projects",
      "experience": "Experience",
      "cv": "CV",
      "anythingAboutMe": "Anything about me",
      "contact": "Contact",
      "connect": "Connect",
      "blogs": "Blogs",
      "email": "Email",
      "navigation": "Footer Navigation",
      "license": "Licensed under",
      "rights": "All rights reserved."
    }
  },
  "notFound": {
    "pageNotFound404": "404 - Page Not Found",
    "oopsPageNotFound": "Oops! Page not found",
    "sorryWeCouldntFindThatPage": "Sorry, we couldn’t find that page",
    "pleaseCheckTheUrlOrGoBackHome": "Please check the URL or go back home",
    "goBack": "Go back",
    "home": "Home",
    "aboutMe": "About me",
    "learnMoreAboutMyBackgroundAndJourney": "Learn more about my background and journey",
    "seeMyWork": "See my work",
    "checkOutTheProjectsIveBuilt": "Check out the projects I've built",
    "contact": "Contact",
    "reachOutForCollaborationOrQuestions": "Reach out for collaboration or questions",
    "explore": "Explore"
  },
  "error": {
    "somethingWentWrong": "Something went wrong!",
    "goBack": "Go back",
    "home": "Home",
    "reportForMe": "Report this error",
    "reportForMeAboutThisError": "Send a report about this error",
    "send": "Send",
    "errorDetails": "Error Details",
    "copyError": "Copy Error",
    "copied": "Copied!",
    "missingQuestion": "You haven't entered a question. Please try again.",
    "invalidInput": "Your question may contain inappropriate content. Please check and try again.",
    "missingThreadId": "Missing conversation ID. Please refresh the page and try again.",
    "failedToDelete": "Something went wrong while deleting the conversation. Please try again later or refresh the page."
  },
  "about": {
    "section": {
      "aboutMe": "About me",
      "education": "Education",
      "skillsTechStack": "Skills / Tech Stack"
    },
    "techStack": {
      "frameworksTitle": "Frameworks",
      "librariesTitle": "Libraries",
      "programmingLanguagesTitle": "Programming Languages",
      "databaseTitle": "Database"
    }
  },
  "project": {
    "details": "Details",
    "gitHub": "GitHub",
    "all": "All",
    "thereAreNoProjectsYet": "There are no projects yet",
    "loadingProjectList": "Loading project list",
    "failedToLoadProjectList": "Failed to load project list Please try again",
    "backToProjects": "Back to projects",
    "noProjectsFound": "No projects have been added yet.",
    "noProjectsMatchYourSearch": "No projects match your current filters or search query.",
    "pageTitle": "Projects",
    "count": "{count, plural, =0 {No projects} one {# project} other {# projects}}",
    "present": "Present",
    "liveDemo": "Live demo",
    "ongoing": "Ongoing",
    "completed": "Completed",
    "undated": "Undated"
  },
  "blog": {
    "details": "Details",
    "all": "All",
    "thereAreNoBlogsYet": "There are no blogs yet",
    "loadingBlogList": "Loading blog list",
    "failedToLoadBlogList": "Failed to load blog list. Please try again",
    "noBlogsFound": "No blogs found yet. Stay tuned for future posts!",
    "noBlogsMatchYourSearch": "No blogs match your current search or filters.",
    "pageTitle": "Blog",
    "count": "{count, plural, =0 {No posts} one {# post} other {# posts}}",
    "showDrafts": "Drafts",
    "showDraftsHint": "Admin only — visitors never see drafts"
  },
  "blogDetails": {
    "failedToLoadBlog": "Failed to load blog",
    "blogNotFoundTitle": "Blog Post Not Found",
    "blogNotFoundDescription": "Sorry, the article you are looking for doesn't exist or has been moved.",
    "backToBlogs": "Back to blogs",
    "goHome": "Go to homepage",
    "relatedProject": "Related Project",
    "viewProject": "View project",
    "views": "{count, plural, =0 {No views} one {# view} other {# views}}",
    "avgRead": "{time}m avg. read",
    "readingTime": "{time} min read",
    "like": "Like",
    "comment": "Comment",
    "share": "Share",
    "pdf": "PDF",
    "downloadPdf": "Download PDF",
    "updatedOn": "updated {date}",
    "comments": "Comments",
    "loadMoreComments": "Loading more...",
    "loadMore": "Load more",
    "signInToComment": "Sign in to comment",
    "postComment": "Post Comment",
    "noCommentsYet": "No comments yet",
    "beTheFirstComment": "Be the first to share your thoughts!",
    "writingComment": "Write a comment...",
    "mustSignInToComment": "Must sign in to comment",
    "posting": "Posting...",
    "postCommentFailed": "Failed to post comment",
    "interactFailed": "Failed to interact the post",
    "justNow": "just now",
    "reply": "Reply",
    "replyTo": "Reply to",
    "cancel": "Cancle",
    "hideCommentFailed": "Failed to delete the comment, try again later",
    "linkCopied": "Link copied to clipboard",
    "home": "Home",
    "allPosts": "All posts",
    "tableOfContents": "On this page",
    "relatedPosts": "Related posts",
    "previousPost": "Previous",
    "nextPost": "Next",
    "aboutTheAuthor": "About the author"
  },
  "contact": {
    "letsWorkTogether": "Let’s work together",
    "feelFreeToReachOutThroughAnyChannel": "Feel free to reach out through any channel",
    "sendMeAnEmail": "Send me an email",
    "or": "Or",
    "sendMeADirectMessage": "Send me a direct message"
  },
  "homepage": {
    "myStory": "My story",
    "moreAboutMyJourney": "More about my journey",
    "selectedProjects": "Selected projects",
    "aFewThingsIveBuiltRecently": "A few things I’ve built recently",
    "viewProject": "View project",
    "viewAllProjects": "View all projects",
    "thereAreNoProjectsYet": "There are no projects yet",
    "haveAnIdeaInMind": "Have an idea in mind?",
    "alwaysInterestedInThoughtfulProjectsAndGoodCollaboration": "Always interested in thoughtful projects and good collaboration.",
    "letsWorkTogether": "Let’s work together",
    "emailMe": "Email me",
    "contactDetails": "Contact details"
  },
  "experience": {
    "title": "Work Experience",
    "updating": "Updating..."
  },
  "components": {
    "expandableText": {
      "showLess": "Show less",
      "showMore": "Show more"
    },
    "projectFilters": {
      "filters": "Filters",
      "reset": "Reset",
      "seeMore": "See more",
      "searchProject": "Search project...",
      "tags": "Tags",
      "techStack": "Tech stack"
    },
    "blogFilters": {
      "filters": "Filters",
      "reset": "Reset",
      "seeMore": "See more",
      "searchBlog": "Search blog...",
      "tags": "Tags"
    },
    "blogCard": {
      "views": "{count, plural, =0 {No views} one {# view} other {# views}}",
      "readingTime": "{time} min read",
      "draft": "Draft"
    },
    "filters": {
      "clearSearch": "Clear search"
    }
  },
  "dashboard": {
    "sidebar": {
      "groups": {
        "overview": "Overview",
        "portfolio": "Portfolio Content",
        "resume": "Resume Data",
        "configuration": "Configuration"
      },
      "items": {
        "dashboard": "Dashboard",
        "profile": "Profile",
        "projects": "Projects",
        "blogs": "Blogs",
        "comments": "Comments",
        "media": "Media Library",
        "companies": "Companies",
        "education": "Education",
        "techStacks": "Tech Stacks",
        "tags": "Tags"
      },
      "actions": {
        "clearCache": "Clear Cache",
        "viewSite": "View Site",
        "signOut": "Sign out",
        "cacheSuccess": "System updated",
        "cacheSuccessDesc": "All caches have been cleared successfully.",
        "cacheError": "Update failed",
        "cacheErrorDesc": "An error occurred while clearing caches."
      }
    },
    "dashboard": {
      "welcome": "Welcome back, {name}! 👋",
      "description": "Manage your personal portfolio and track your content performance."
    },
    "contactGallery": {
      "title": "Recent Inquiries",
      "description": "Direct messages from your portfolio contact form.",
      "messageCount": "{count, plural, =1 {1 Message} other {# Messages}}",
      "searchPlaceholder": "Search messages...",
      "noMessages": "No messages found",
      "noSubject": "No Subject",
      "clickMore": "Click to read more",
      "subjectLabel": "Subject",
      "messageLabel": "Message",
      "noSubjectProvided": "No subject provided",
      "close": "Close"
    },
    "blog": {
      "title": "Blog Posts",
      "description": "Create and manage your articles, drafts, and published content.",
      "createButton": "New Blog",
      "emptyTitle": "No blogs found",
      "emptyDescription": "Create your first blog.",
      "deleteTitle": "Delete Blog?",
      "deleteDescription": "This action cannot be undone.",
      "loadError": "Failed to load this post.",
      "dialog": {
        "editTitle": "Edit blog",
        "createTitle": "Create blog",
        "editDescription": "Update the post and its translations, then save.",
        "createDescription": "Write the post, add translations, and publish when ready.",
        "retry": "Retry",
        "loadingLabel": "Loading blog",
        "cancelButton": "Cancel",
        "saveButton": "Save changes",
        "createSubmitButton": "Create post"
      },
      "toast": {
        "created": "Blog created",
        "updated": "Blog updated",
        "deleted": "Blog deleted",
        "saveError": "Failed to save blog",
        "deleteError": "Could not delete blog"
      },
      "form": {
        "draftFound": "Unsaved draft from {time} found.",
        "restore": "Restore",
        "discard": "Discard",
        "contentTranslationsTitle": "Content Translations",
        "titleLabel": "Title",
        "titlePlaceholder": "Post title...",
        "descriptionLabel": "Short Description",
        "descriptionPlaceholder": "Brief summary of the post...",
        "bodyLabel": "Body Content",
        "savePost": "Save Post"
      },
      "meta": {
        "slugLabel": "Slug",
        "slugPlaceholder": "my-awesome-blog",
        "projectLabel": "Related Project",
        "projectPlaceholder": "Select a project (optional)",
        "projectNone": "None",
        "publishedLabel": "Published",
        "coverImageLabel": "Cover Image",
        "tagsLabel": "Tags",
        "tagsPlaceholder": "Select tags..."
      },
      "overview": {
        "viewsChartTitle": "Views — last 30 days",
        "noViewsYet": "No views yet",
        "topPostsTitle": "Top posts",
        "dayViewsLabel": "{date}: {count, plural, =0 {No views} one {# view} other {# views}}",
        "topBlogViewsLabel": "{title}: {count, plural, =0 {No views} one {# view} other {# views}}",
        "likesLabel": "Likes",
        "clapsLabel": "Claps",
        "blogViewsLabel": "Blog Views",
        "allTimeSub": "All time",
        "last30DaysSub": "{count, number} in last 30 days"
      }
    },
    "comment": {
      "title": "Comments",
      "description": "Moderate comments left on your blogs and projects",
      "emptyTitle": "No comments yet",
      "emptyDescription": "Comments on your blogs and projects will show up here.",
      "avatarFallbackAlt": "User",
      "source": {
        "blog": "Blog: {title}",
        "project": "Project: {title}",
        "untitledProject": "Untitled",
        "unknown": "Unknown source"
      },
      "status": {
        "hidden": "Hidden"
      },
      "actions": {
        "restore": "Restore",
        "hide": "Hide"
      },
      "toast": {
        "hidden": "Comment hidden",
        "restored": "Comment restored",
        "updateError": "Error updating comment"
      },
      "dialog": {
        "hideTitle": "Hide Comment",
        "hideDescription": "This comment will no longer be visible to visitors. You can restore it later."
      }
    },
    "common": {
      "nav": {
        "soonBadge": "Soon"
      },
      "stats": {
        "messagesLabel": "Messages",
        "messagesSub": "{count, number} new",
        "projectsLabel": "Projects",
        "projectsSub": "Live works",
        "blogsLabel": "Blogs",
        "blogsSub": "Articles",
        "educationLabel": "Education",
        "educationSub": "Certificates",
        "companiesLabel": "Companies",
        "techStackLabel": "Tech Stack",
        "tagsLabel": "Tags"
      }
    },
    "company": {
      "title": "Work Experience",
      "description": "Maintain your professional timeline and company records",
      "createButton": "Add Experience",
      "emptyTitle": "No work experience",
      "emptyDescription": "Start by adding the first company you worked with.",
      "emptyAction": "Add Your First Entry",
      "present": "Present",
      "rolesBadge": "{count, plural, =1 {# Role} other {# Roles}}",
      "techStackBadge": "{count, number} Tech",
      "deleteTitle": "Delete work experience?",
      "deleteDescription": "Are you sure you want to delete <name></name> and all of its roles?",
      "toast": {
        "created": "Work experience created",
        "updated": "Work experience updated",
        "deleted": "Work experience deleted",
        "saveError": "Failed to save work experience",
        "deleteError": "Could not delete work experience"
      },
      "dialog": {
        "createTitle": "Add Work Experience",
        "editTitle": "Edit Work Experience",
        "logoLabel": "Company Logo",
        "companyLabel": "Company Name",
        "locationLabel": "Location",
        "startDateLabel": "Start Date",
        "endDateLabel": "End Date",
        "techStackLabel": "Tech Stack",
        "techStackPlaceholder": "Select tech stack",
        "translationsTitle": "Translations",
        "descriptionLabel": "Description",
        "rolesTitle": "Roles",
        "addRoleButton": "Add Role",
        "saveButton": "Save"
      },
      "role": {
        "fallbackTitle": "Role {index, number}",
        "removeButton": "Remove role",
        "startDateLabel": "Start Date",
        "endDateLabel": "End Date",
        "titleLabel": "Role Title",
        "descriptionLabel": "Description",
        "tasksTitle": "Tasks",
        "addTaskButton": "Add Task"
      },
      "task": {
        "sortLabel": "Sort",
        "contentLabel": "Task",
        "removeButton": "Remove task"
      }
    },
    "education": {
      "title": "Education",
      "description": "Manage your academic background",
      "createButton": "Add Education",
      "emptyTitle": "No education entries",
      "emptyDescription": "Start by adding your first academic achievement.",
      "emptyAction": "Add Your First Entry",
      "untitled": "Untitled Education",
      "present": "Present",
      "ongoing": "Ongoing",
      "achievementCount": "{count, plural, =1 {1 Achievement} other {# Achievements}}",
      "deleteTitle": "Delete education?",
      "deleteDescription": "Are you sure you want to delete <name></name>?",
      "toast": {
        "created": "Education created",
        "updated": "Education updated",
        "deleted": "Education deleted",
        "saveError": "Failed to save education",
        "deleteError": "Could not delete education"
      },
      "dialog": {
        "createTitle": "Add education",
        "editTitle": "Edit education",
        "createDescription": "Add a school or degree, then list what you achieved there.",
        "editDescription": "Update this entry and the achievements listed under it.",
        "logoLabel": "Institution Logo",
        "startDateLabel": "Start Date",
        "endDateLabel": "End Date",
        "translationsTitle": "Translations",
        "translationsDescription": "One tab per language. Visitors see the tab matching their locale.",
        "schoolLabel": "School / Degree",
        "descriptionLabel": "Description",
        "descriptionPlaceholder": "A short summary of this program…",
        "cancelButton": "Cancel",
        "saveButton": "Save changes",
        "createSubmitButton": "Add education"
      },
      "achievements": {
        "title": "Achievements",
        "reorderHint": "Drag the handle to reorder — this is the order visitors see.",
        "addButton": "Add",
        "emptyText": "No achievements yet.",
        "addFirstButton": "Add the first one",
        "untitled": "Untitled achievement",
        "reorderAriaLabel": "Reorder achievement {index, number} of {total, number}",
        "removeAriaLabel": "Remove achievement",
        "imagesLabel": "Images",
        "titleLabel": "Title",
        "contentLabel": "Content",
        "contentPlaceholder": "Describe this achievement…"
      }
    },
    "media": {
      "title": "Media Library",
      "description": "Centralized storage for your portfolio assets and banner images.",
      "addButton": "Add Media",
      "empty": {
        "title": "No media found",
        "description": "Your library is empty. Upload your first image to get started."
      },
      "dialog": {
        "uploadTitle": "Upload Media",
        "deleteTitle": "Delete Media",
        "deleteDescription": "This will permanently delete this media file. This action cannot be undone."
      },
      "picker": {
        "libraryLabel": "Library",
        "uploadButton": "Upload",
        "uploadAssetsTitle": "Upload Assets",
        "clearAll": "Clear All",
        "selectMedia": "Select Media",
        "selectedCount": "{count, plural, =1 {1 selected} other {# selected}}",
        "moreCount": "{count, plural, =1 {+ 1 more} other {+ # more}}",
        "clickToManage": "Click to manage",
        "clickToChange": "Click to change",
        "chooseFromLibrary": "Upload or choose from library",
        "selectedAlt": "Selected",
        "loadMore": "Load More"
      },
      "upload": {
        "dropzoneText": "Click or drag images here",
        "invalidTypeTitle": "Invalid type",
        "invalidTypeDescription": "{fileName} is not an image.",
        "fileTooLargeTitle": "File too large",
        "fileTooLargeDescription": "{fileName} exceeds {maxSize, number}MB.",
        "successTitle": "Success",
        "successDescription": "All images uploaded.",
        "uploadFailedTitle": "Upload failed",
        "uploadButton": "{count, plural, =1 {Upload 1 File} other {Upload # Files}}"
      },
      "toast": {
        "uploadSuccess": "Upload successful",
        "uploadError": "Upload failed",
        "deleteSuccess": "Media deleted",
        "deleteError": "Could not delete media"
      }
    },
    "note": {
      "title": "Notes",
      "description": "Your private notes. Nothing here is ever published.",
      "untitled": "Untitled",
      "untitledFolder": "New folder",
      "loading": "Loading note…",
      "emptySelection": "Select a note, or create one.",
      "folderNotEditable": "This is a folder — it has no document to edit.",
      "backToList": "All notes",
      "tree": {
        "expandAriaLabel": "Expand",
        "collapseAriaLabel": "Collapse",
        "actionsAriaLabel": "Note actions",
        "treeAriaLabel": "Note tree",
        "draftNoteLabel": "New note name",
        "draftFolderLabel": "New folder name",
        "renameInputLabel": "Rename"
      },
      "fields": {
        "title": "Note title",
        "titlePlaceholder": "Untitled"
      },
      "actions": {
        "create": "New note",
        "newFolder": "New folder",
        "newNoteInside": "New note inside",
        "newFolderInside": "New folder inside",
        "rename": "Rename",
        "pin": "Pin",
        "unpin": "Unpin",
        "archive": "Archive",
        "restore": "Restore",
        "delete": "Delete",
        "deleteForever": "Delete permanently",
        "share": "Share",
        "showArchived": "Archived",
        "hideArchived": "Back to notes"
      },
      "status": {
        "saving": "Saving…",
        "saved": "Saved",
        "error": "Not saved",
        "retry": "Retry"
      },
      "view": {
        "label": "Editor view",
        "editor": "Editor",
        "markdown": "Markdown"
      },
      "properties": {
        "title": "Properties",
        "status": "Status",
        "statusPlaceholder": "e.g. draft",
        "presets": {
          "draft": "Draft",
          "active": "Active",
          "done": "Done"
        },
        "key": "Property name",
        "keyPlaceholder": "Name",
        "value": "Property value",
        "valuePlaceholder": "Value",
        "valueFor": "Value of {key}",
        "add": "Add property",
        "remove": "Remove {key}",
        "labels": "Labels",
        "labelsPlaceholder": "Add label…",
        "removeLabel": "Remove label {name}"
      },
      "cheatSheet": {
        "open": "Markdown help",
        "title": "Markdown cheat sheet",
        "description": "Type these as you write — they turn into formatting instantly.",
        "noSyntax": "Drag & drop / paste",
        "sections": {
          "basics": "Basics",
          "blocks": "Blocks",
          "linksMedia": "Links & media",
          "tables": "Tables",
          "math": "Math"
        },
        "rows": {
          "heading": "Heading — one # per level, then a space.",
          "bold": "Bold text.",
          "italic": "Italic text.",
          "strike": "Strikethrough.",
          "code": "Inline code.",
          "quote": "Blockquote — type > then a space.",
          "list": "Bulleted or numbered list.",
          "fence": "Code block — three backticks, optional language.",
          "rule": "Horizontal divider.",
          "noteLink": "Link to another note — type [[ and pick one.",
          "image": "Drop an image file or paste a screenshot to insert it.",
          "table": "Paste a markdown table and it becomes a real table.",
          "mathInline": "Inline math, rendered as you type.",
          "mathBlock": "Math block on its own line, in display style."
        }
      },
      "rename": {
        "title": "Rename",
        "label": "New name",
        "save": "Save",
        "cancel": "Cancel"
      },
      "sidebar": {
        "title": "Note panel",
        "toc": "Contents",
        "links": "Links",
        "tocEmpty": "Headings you add will show up here."
      },
      "explorer": {
        "viewMode": "View",
        "modes": {
          "tree": "Tree",
          "flat": "Flat list",
          "grouped": "Grouped"
        },
        "sortLabel": "Sort by",
        "sort": {
          "updated": "Last edited",
          "created": "Date created",
          "title": "Title"
        },
        "groupByLabel": "Group by",
        "groupBy": {
          "status": "Status",
          "label": "Label"
        },
        "noLabel": "No label",
        "dropToRoot": "Drop here to move to top level",
        "resizeAriaLabel": "Resize the note list",
        "collapseSidebar": "Hide note list",
        "expandSidebar": "Show note list",
        "breadcrumbAriaLabel": "Note location"
      },
      "search": {
        "trigger": "Search notes",
        "placeholder": "Search your notes…",
        "loading": "Searching…",
        "empty": "No notes match.",
        "actionsHeading": "Actions",
        "actionNewNote": "New note",
        "actionCheatSheet": "Markdown help"
      },
      "archive": {
        "title": "Archived",
        "empty": "Nothing archived."
      },
      "delete": {
        "title": "Delete permanently?",
        "description": "“{title}” will be deleted for good. This cannot be undone.",
        "descriptionWithChildren": "“{title}” and {count, plural, one {its # nested note} other {its # nested notes}} will be deleted for good. This cannot be undone.",
        "descriptionShared": "{count, plural, one {# person} other {# people}} can currently open this. Deleting it removes their access too.",
        "confirm": "Delete permanently",
        "cancel": "Cancel"
      },
      "archiveConfirm": {
        "title": "Move “{title}” to the archive?",
        "description": "You can restore it from the Archived view.",
        "descriptionWithChildren": "{count, plural, one {Its # nested note} other {Its # nested notes}} will go with it. You can restore them from the Archived view.",
        "confirm": "Move to archive",
        "cancel": "Cancel"
      },
      "move": {
        "sharedTitle": "Move into a shared folder?",
        "sharedDescription": "“{title}” will become visible to {count, plural, one {# person} other {# people}} who can already open the destination.",
        "sharedConfirm": "Move anyway",
        "sharedCancel": "Cancel"
      },
      "share": {
        "title": "Share “{title}”",
        "descriptionNote": "People you invite can open this note only. Nothing else in your space becomes visible to them.",
        "descriptionFolder": "People you invite can open this folder and everything inside it — including notes you move in later.",
        "emailLabel": "Email address",
        "emailPlaceholder": "name@example.com",
        "roleViewer": "Can view",
        "roleEditor": "Can edit",
        "invite": "Invite",
        "pending": "Pending",
        "accepted": "Accepted",
        "revoke": "Remove access",
        "empty": "Not shared with anyone yet.",
        "loading": "Loading people…",
        "failed": "Could not load who has access."
      },
      "links": {
        "title": "Links",
        "outgoing": "Links out",
        "incoming": "Mentioned by",
        "empty": "No links yet.",
        "open": "Show links",
        "close": "Hide links",
        "deleted": "Deleted note",
        "expandAriaLabel": "Expand links",
        "collapseAriaLabel": "Collapse links",
        "insert": "Link to note",
        "pickerPlaceholder": "Link to a note…",
        "pickerEmpty": "No notes match.",
        "pickerCreate": "Create note “{title}”"
      },
      "toasts": {
        "archived": "Moved to archive",
        "restored": "Note restored",
        "deleted": "Note deleted"
      },
      "empty": {
        "title": "No notes yet."
      },
      "errors": {
        "load": "Could not load your notes.",
        "create": "Could not create the note.",
        "save": "Could not save the note.",
        "archive": "Could not archive the note.",
        "restore": "Could not restore the note.",
        "delete": "Could not delete the note.",
        "links": "Could not load links.",
        "ancestors": "Could not load the note's location."
      },
      "graph": {
        "title": "Knowledge graph",
        "description": "Every note, and the links between them.",
        "empty": "No notes to plot yet — write a few and connect them with [[.",
        "loadError": "Couldn't load the graph. Reload to try again.",
        "legendHint": "Scroll to zoom, drag to pan, click a node to open it.",
        "nodeCount": "{count, plural, one {# note} other {# notes}}",
        "edgeCount": "{count, plural, one {# link} other {# links}}",
        "loading": "Loading knowledge graph…"
      },
      "export": {
        "label": "Export",
        "markdown": "Download .md",
        "pdf": "Print / Save as PDF",
        "notReady": "The note is still loading."
      }
    },
    "space": {
      "title": "Space",
      "navAriaLabel": "Workspace navigation",
      "openNav": "Open workspace navigation",
      "items": {
        "hub": "Overview",
        "notes": "Notes",
        "graph": "Graph"
      },
      "actions": {
        "dashboard": "Dashboard",
        "signOut": "Sign out"
      },
      "hub": {
        "greeting": "Welcome back, {name}",
        "subtitle": "Your private workspace",
        "stats": {
          "ariaLabel": "Workspace statistics",
          "notes": "Notes",
          "links": "Links between notes",
          "archived": "In trash"
        },
        "recent": {
          "title": "Recently edited",
          "empty": "Nothing here yet — create your first note.",
          "untitled": "Untitled"
        },
        "modules": {
          "notesTitle": "Notes",
          "notesDescription": "Interconnected notes with backlinks, math, and markdown.",
          "graphTitle": "Knowledge graph",
          "graphDescription": "See how your notes connect — and which ones don't yet."
        },
        "errors": {
          "load": "Couldn't load your workspace overview. Reload to try again."
        },
        "loading": "Loading workspace…"
      }
    },
    "project": {
      "title": "Projects",
      "description": "Manage your portfolio gallery, case studies, and deployment links.",
      "createButton": "New Project",
      "emptyTitle": "No projects found",
      "emptyDescription": "Create your first project to showcase your work.",
      "deleteTitle": "Delete Project?",
      "deleteDescription": "This action cannot be undone. This will permanently delete the project and remove its data from our servers.",
      "dialog": {
        "createTitle": "New Project",
        "editTitle": "Edit Project",
        "slugLabel": "Slug",
        "slugPlaceholder": "my-awesome-project",
        "startDateLabel": "Start Date",
        "endDateLabel": "End Date",
        "githubLinkLabel": "GitHub Link",
        "githubLinkPlaceholder": "https://github.com/...",
        "liveLinkLabel": "Live Link",
        "liveLinkPlaceholder": "https://...",
        "publishedLabel": "Published",
        "techStackLabel": "Tech Stack",
        "techStackPlaceholder": "Select tech stack",
        "tagsLabel": "Tags",
        "tagsPlaceholder": "Select tags",
        "translationsLabel": "Content Translations",
        "titleLabel": "Title",
        "descriptionLabel": "Description",
        "descriptionPlaceholder": "What this project is, and what it does…",
        "saveButton": "Save Project",
        "savingButton": "Saving..."
      },
      "coauthors": {
        "title": "Co-authors",
        "addButton": "Add Co-author",
        "nameLabel": "Name",
        "namePlaceholder": "Jane Doe",
        "emailLabel": "Email",
        "emailPlaceholder": "jane@example.com",
        "removeButton": "Remove co-author"
      },
      "toast": {
        "created": "Project created",
        "updated": "Project updated",
        "deleted": "Project deleted",
        "saveError": "Failed to save project",
        "deleteError": "Could not delete project"
      }
    },
    "tag": {
      "title": "Tags",
      "description": "Create and manage custom taxonomies to categorize your content.",
      "createButton": "Create New Tag",
      "emptyTitle": "No tags found",
      "emptyDescription": "Create tags to organize your content library.",
      "emptyAction": "Create First Tag",
      "deleteTitle": "Delete Tag",
      "deleteDescription": "This will permanently delete the tag <name></name>. This action cannot be undone.",
      "dialog": {
        "createTitle": "Create Tag",
        "editTitle": "Edit Tag",
        "slugLabel": "Slug",
        "slugPlaceholder": "reactjs",
        "translationsLabel": "Translations",
        "addButton": "Add",
        "languageLabel": "Language",
        "languagePlaceholder": "en",
        "nameLabel": "Name",
        "namePlaceholder": "React",
        "cancelButton": "Cancel",
        "saveButton": "Save"
      },
      "toast": {
        "created": "Tag created",
        "updated": "Tag updated",
        "deleted": "Tag deleted",
        "saveError": "Failed to save tag",
        "deleteError": "Could not delete tag"
      }
    },
    "techStack": {
      "title": "Tech Stack",
      "description": "Maintain the list of technologies, frameworks, and tools you use.",
      "createButton": "Add TechStack",
      "emptyTitle": "No tech stacks found",
      "otherGroup": "Other",
      "deleteTitle": "Remove Tech stack",
      "deleteDescription": "Are you sure you want to remove <name></name>? This will hide it from your tech stack showcase.",
      "dialog": {
        "createTitle": "Add Tech Stack",
        "editTitle": "Edit Tech Stack",
        "nameLabel": "Name",
        "slugLabel": "Slug",
        "groupLabel": "Group",
        "logoLabel": "Logo",
        "saveButton": "Save"
      },
      "toast": {
        "created": "Tech stack created",
        "updated": "Tech stack updated",
        "deleted": "Tech stack deleted",
        "saveError": "Failed to save tech stack",
        "deleteError": "Could not delete tech stack"
      }
    },
    "userProfile": {
      "title": "Profile Settings",
      "description": "Manage your global identity.",
      "resetButton": "Reset",
      "cancelButton": "Cancel",
      "saveButton": "Save",
      "translations": {
        "heading": "Translations",
        "addLanguage": "Add Language",
        "newTabLabel": "NEW",
        "languageLabel": "Language",
        "languagePlaceholder": "en, vi..."
      },
      "commonInfo": {
        "heading": "Common Information",
        "description": "General profile settings",
        "birthdateLabel": "Birthdate"
      },
      "identity": {
        "sectionTitle": "Identity",
        "firstNameLabel": "First Name",
        "lastNameLabel": "Last Name",
        "displayNameLabel": "Display Name"
      },
      "content": {
        "sectionTitle": "Content",
        "greetingLabel": "Greeting",
        "taglineLabel": "Tagline",
        "taglinePlaceholder": "Hi, I'm...",
        "bioLabel": "Short Bio",
        "bioPlaceholder": "Fullstack developer..."
      },
      "quote": {
        "sectionTitle": "Quote",
        "quoteLabel": "Quote",
        "quotePlaceholder": "Enter an inspiring quote...",
        "authorLabel": "Author"
      },
      "aboutMe": {
        "sectionTitle": "About Me"
      },
      "socialLinks": {
        "heading": "Social Links",
        "description": "Add your social profiles",
        "addLink": "Add Link",
        "emptyTitle": "No social links yet",
        "emptyAction": "Add your first link",
        "platformPlaceholder": "GitHub",
        "urlPlaceholder": "https://...",
        "removeConfirm": "Remove this link?"
      },
      "toast": {
        "updated": "Profile updated",
        "saveError": "Save failed"
      }
    },
    "shared": {
      "translationTabs": {
        "addLanguage": "Add Language",
        "removeLanguage": "Remove Language",
        "languageLabel": "Language",
        "languagePlaceholder": "en, vi..."
      },
      "managerListState": {
        "loading": "Loading…",
        "errorTitle": "Something went wrong",
        "errorDescription": "The list could not be loaded. Please try again.",
        "retry": "Retry"
      },
      "confirmDelete": {
        "actionText": "Delete",
        "cancelText": "Cancel"
      }
    }
  },
  "auth": {
    "signInTitle": "Sign in to your account",
    "orContinueWith": "Or continue with",
    "signInWithGithub": "Continue with GitHub",
    "signInWithGoogle": "Continue with Google",
    "emailPlaceholder": "name@example.com",
    "sendMagicLink": "Send Magic Link",
    "accessDenied": "That account is not authorized to access this dashboard.",
    "signInFailed": "Sign in could not be completed. Please try again."
  },
  "share": {
    "invite": {
      "title": "Open a shared note",
      "description": "Sign in with the email address the note was shared with. A link sent to any other address will not open it.",
      "emailPlaceholder": "name@example.com",
      "submit": "Send me a link",
      "sent": "If that address has been invited, a sign-in link is on its way. Check your spam folder too.",
      "failed": "Something went wrong. Please try again.",
      "orContinueWith": "Or continue with"
    },
    "inbox": {
      "title": "Shared with you",
      "description": "Notes and folders other people have given you access to.",
      "empty": "Nothing has been shared with you yet.",
      "failed": "Could not load what has been shared with you.",
      "sharedBy": "Shared by {owner}",
      "roleViewer": "Can view",
      "roleEditor": "Can edit"
    },
    "note": {
      "notFound": "This note is no longer available.",
      "sharedWithYouLabel": "Shared with you",
      "breadcrumbAriaLabel": "Note path",
      "expand": "Expand",
      "collapse": "Collapse",
      "loading": "Loading…",
      "readOnly": "You have view-only access.",
      "backToInbox": "Shared with you",
      "saving": "Saving…",
      "saved": "Saved",
      "saveFailed": "Not saved",
      "outOfScopeLink": "This link points outside what was shared with you.",
      "emptyFolder": "This folder is empty.",
      "selectNote": "Select a note."
    }
  },
  "email": {
    "signIn": {
      "title": "Sign in to your account",
      "description": "Click the button below to access your dashboard.",
      "button": "Sign in",
      "expire": "This link will expire in 24 hours.",
      "ignore": "If you did not request this email, you can safely ignore it."
    },
    "sharedNote": {
      "subject": "{name} shared a note with you",
      "title": "A note has been shared with you",
      "description": "{owner} shared \"{title}\" with you. Sign in with this email address to open it.",
      "button": "Open the note",
      "ignore": "If you weren't expecting this, you can safely ignore this email."
    }
  }
};
export default messages;