// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "metadata": {
    "title": "Phu Luong",
    "description": "Showcasing passion, experience, and projects — one byte at a time.",
    "about": {
      "title": "About Me",
      "description": "A journey through my background, education, and technical stack.",
      "keywords": "About me, Introduction, Background, Education, Tech stack"
    },
    "experience": {
      "title": "Experience",
      "description": "A professional timeline of my roles and hands-on contributions.",
      "keywords": "Experience, Work history, Career timeline, Roles, Employment"
    },
    "projects": {
      "title": "Projects",
      "description": "A collection of my work, from academic builds to real-world solutions.",
      "keywords": "Projects, Side projects, Portfolio, Case studies, Open source"
    },
    "contact": {
      "title": "Contact",
      "description": "Let's connect for collaborations or professional inquiries.",
      "keywords": "Contact, Get in touch, Collaboration, Hire me, Email"
    },
    "blogs": {
      "title": "Blog",
      "description": "Insights, tutorials, and reflections on technology and development.",
      "keywords": "Blog, Articles, Writing, Tutorials, Software development"
    }
  },
  "global": {
    "tableOfContent": "Table of Content",
    "userToggle": {
      "signOut": "Sign out",
      "admin": "Admin",
      "viewer": "Viewer",
      "openAccount": "Open account menu"
    },
    "i18nToggle": {
      "toggleLanguage": "Toggle language",
      "vietnamese": "Vietnamese",
      "english": "English",
      "french": "French"
    },
    "modeToggle": {
      "toggleTheme": "Toggle theme",
      "light": "Light",
      "dark": "Dark",
      "system": "System"
    },
    "search": {
      "searchProjects": "Search projects",
      "all": "All"
    },
    "header": {
      "skipToContent": "Skip to main content",
      "nav": {
        "home": "Home",
        "about": "About",
        "experience": "Experience",
        "projects": "Projects",
        "blogs": "Blogs",
        "hobbies": "Hobbies",
        "more": "More",
        "letsTalk": "Let's talk",
        "askMe": "Ask Me",
        "anythingAboutMe": "Anything about me",
        "cv": "CV"
      }
    },
    "footer": {
      "home": "Home",
      "builtBy": "Built by",
      "openSource": "Open source on",
      "links": "Quick Links",
      "about": "About",
      "projects": "Projects",
      "experience": "Experience",
      "cv": "CV",
      "anythingAboutMe": "Anything about me",
      "contact": "Contact",
      "connect": "Connect",
      "blogs": "Blogs",
      "email": "Email",
      "navigation": "Footer Navigation",
      "license": "Licensed under",
      "rights": "All rights reserved."
    }
  },
  "notFound": {
    "pageNotFound404": "404 - Page Not Found",
    "oopsPageNotFound": "Oops! Page not found",
    "sorryWeCouldntFindThatPage": "Sorry, we couldn’t find that page",
    "pleaseCheckTheUrlOrGoBackHome": "Please check the URL or go back home",
    "goBack": "Go back",
    "home": "Home",
    "aboutMe": "About me",
    "learnMoreAboutMyBackgroundAndJourney": "Learn more about my background and journey",
    "seeMyWork": "See my work",
    "checkOutTheProjectsIveBuilt": "Check out the projects I've built",
    "contact": "Contact",
    "reachOutForCollaborationOrQuestions": "Reach out for collaboration or questions",
    "explore": "Explore"
  },
  "error": {
    "somethingWentWrong": "Something went wrong!",
    "goBack": "Go back",
    "home": "Home",
    "reportForMe": "Report this error",
    "reportForMeAboutThisError": "Send a report about this error",
    "send": "Send",
    "errorDetails": "Error Details",
    "copyError": "Copy Error",
    "copied": "Copied!",
    "missingQuestion": "You haven't entered a question. Please try again.",
    "invalidInput": "Your question may contain inappropriate content. Please check and try again.",
    "missingThreadId": "Missing conversation ID. Please refresh the page and try again.",
    "failedToDelete": "Something went wrong while deleting the conversation. Please try again later or refresh the page."
  },
  "about": {
    "section": {
      "aboutMe": "About me",
      "education": "Education",
      "skillsTechStack": "Skills / Tech Stack"
    },
    "techStack": {
      "frameworksTitle": "Frameworks",
      "librariesTitle": "Libraries",
      "programmingLanguagesTitle": "Programming Languages",
      "databaseTitle": "Database"
    },
    "education": {
      "present": "Present",
      "ongoing": "Ongoing"
    }
  },
  "project": {
    "details": "Details",
    "gitHub": "GitHub",
    "all": "All",
    "thereAreNoProjectsYet": "There are no projects yet",
    "loadingProjectList": "Loading project list",
    "failedToLoadProjectList": "Failed to load project list Please try again",
    "backToProjects": "Back to projects",
    "noProjectsFound": "No projects have been added yet.",
    "noProjectsMatchYourSearch": "No projects match your current filters or search query.",
    "pageTitle": "Projects",
    "count": "{count, plural, =0 {No projects} one {# project} other {# projects}}",
    "present": "Present",
    "liveDemo": "Live demo",
    "ongoing": "Ongoing",
    "completed": "Completed",
    "undated": "Undated"
  },
  "blog": {
    "details": "Details",
    "all": "All",
    "thereAreNoBlogsYet": "There are no blogs yet",
    "loadingBlogList": "Loading blog list",
    "failedToLoadBlogList": "Failed to load blog list. Please try again",
    "noBlogsFound": "No blogs found yet. Stay tuned for future posts!",
    "noBlogsMatchYourSearch": "No blogs match your current search or filters.",
    "pageTitle": "Blog",
    "count": "{count, plural, =0 {No posts} one {# post} other {# posts}}",
    "showDrafts": "Drafts",
    "showDraftsHint": "Admin only — visitors never see drafts"
  },
  "blogDetails": {
    "failedToLoadBlog": "Failed to load blog",
    "blogNotFoundTitle": "Blog Post Not Found",
    "blogNotFoundDescription": "Sorry, the article you are looking for doesn't exist or has been moved.",
    "backToBlogs": "Back to blogs",
    "goHome": "Go to homepage",
    "relatedProject": "Related Project",
    "viewProject": "View project",
    "views": "{count, plural, =0 {No views} one {# view} other {# views}}",
    "avgRead": "{time}m avg. read",
    "readingTime": "{time} min read",
    "like": "Like",
    "comment": "Comment",
    "share": "Share",
    "pdf": "PDF",
    "downloadPdf": "Download PDF",
    "updatedOn": "updated {date}",
    "comments": "Comments",
    "loadMoreComments": "Loading more...",
    "loadMore": "Load more",
    "signInToComment": "Sign in to comment",
    "postComment": "Post Comment",
    "noCommentsYet": "No comments yet",
    "beTheFirstComment": "Be the first to share your thoughts!",
    "writingComment": "Write a comment...",
    "mustSignInToComment": "Must sign in to comment",
    "posting": "Posting...",
    "postCommentFailed": "Failed to post comment",
    "interactFailed": "Failed to interact the post",
    "justNow": "just now",
    "reply": "Reply",
    "replyTo": "Reply to",
    "cancel": "Cancle",
    "hideCommentFailed": "Failed to delete the comment, try again later",
    "linkCopied": "Link copied to clipboard",
    "home": "Home",
    "allPosts": "All posts",
    "tableOfContents": "On this page",
    "references": "References",
    "relatedPosts": "Related posts",
    "previousPost": "Previous",
    "nextPost": "Next",
    "aboutTheAuthor": "About the author"
  },
  "contact": {
    "letsWorkTogether": "Let’s work together",
    "feelFreeToReachOutThroughAnyChannel": "Feel free to reach out through any channel",
    "sendMeADirectMessage": "Send me a direct message",
    "channels": {
      "title": "Channels",
      "opensInNewTab": "(opens in a new tab)",
      "errorTitle": "Channels are unavailable",
      "errorDescription": "The contact channels could not be loaded. The message form still works.",
      "emptyTitle": "No channels listed yet",
      "emptyDescription": "Nothing has been published here yet — use the message form instead."
    },
    "form": {
      "name": "Name",
      "namePlaceholder": "Your name",
      "email": "Email",
      "emailPlaceholder": "email@example.com",
      "subject": "Subject",
      "optional": "optional",
      "subjectPlaceholder": "What is this regarding?",
      "message": "Message",
      "messagePlaceholder": "Tell me what you have in mind…",
      "messageCounter": "{count} / {max}",
      "submit": "Send message",
      "submitting": "Sending…",
      "successTitle": "Message sent",
      "successDescription": "Thanks for reaching out — I’ll reply to the address you gave.",
      "errorTitle": "Message not sent",
      "errors": {
        "invalid": "Please check the fields above and try again.",
        "rateLimited": "Too many messages sent. Please try again in a few minutes.",
        "unknown": "Something went wrong. Please try again."
      }
    },
    "validation": {
      "nameTooShort": "Name is too short",
      "nameTooLong": "Name is too long",
      "emailInvalid": "Invalid email address",
      "subjectTooLong": "Subject is too long",
      "messageTooShort": "Message must be at least 10 characters",
      "messageTooLong": "Message is too long"
    }
  },
  "homepage": {
    "myStory": "My story",
    "moreAboutMyJourney": "More about my journey",
    "selectedProjects": "Selected projects",
    "aFewThingsIveBuiltRecently": "A few things I’ve built recently",
    "viewProject": "View project",
    "viewAllProjects": "View all projects",
    "thereAreNoProjectsYet": "There are no projects yet",
    "haveAnIdeaInMind": "Have an idea in mind?",
    "alwaysInterestedInThoughtfulProjectsAndGoodCollaboration": "Always interested in thoughtful projects and good collaboration.",
    "letsWorkTogether": "Let’s work together",
    "emailMe": "Email me",
    "contactDetails": "Contact details"
  },
  "experience": {
    "title": "Work Experience",
    "updating": "Updating...",
    "present": "Present"
  },
  "components": {
    "expandableText": {
      "showLess": "Show less",
      "showMore": "Show more"
    },
    "projectFilters": {
      "filters": "Filters",
      "reset": "Reset",
      "seeMore": "See more",
      "searchProject": "Search project...",
      "tags": "Tags",
      "techStack": "Tech stack"
    },
    "blogFilters": {
      "filters": "Filters",
      "reset": "Reset",
      "seeMore": "See more",
      "searchBlog": "Search blog...",
      "tags": "Tags"
    },
    "blogCard": {
      "views": "{count, plural, =0 {No views} one {# view} other {# views}}",
      "readingTime": "{time} min read",
      "draft": "Draft"
    },
    "filters": {
      "clearSearch": "Clear search"
    },
    "pagination": {
      "pageLabel": "Page {page, number} of {totalPages, number}",
      "previous": "Previous",
      "next": "Next"
    }
  },
  "dashboard": {
    "sidebar": {
      "navAriaLabel": "Dashboard navigation",
      "openNav": "Open dashboard navigation",
      "groups": {
        "overview": "Overview",
        "portfolio": "Portfolio Content",
        "resume": "Resume Data",
        "configuration": "Configuration"
      },
      "items": {
        "dashboard": "Dashboard",
        "profile": "Profile",
        "projects": "Projects",
        "blogs": "Blogs",
        "comments": "Comments",
        "media": "Media Library",
        "companies": "Companies",
        "education": "Education",
        "techStacks": "Tech Stacks",
        "tags": "Tags"
      },
      "actions": {
        "clearCache": "Clear Cache",
        "viewSite": "View Site",
        "signOut": "Sign out",
        "cacheSuccess": "System updated",
        "cacheSuccessDesc": "All caches have been cleared successfully.",
        "cacheError": "Update failed",
        "cacheErrorDesc": "An error occurred while clearing caches."
      }
    },
    "dashboard": {
      "welcome": "Welcome back, {name}! 👋",
      "description": "Manage your personal portfolio and track your content performance.",
      "analyticsTitle": "Analytics",
      "analyticsDescription": "Blog views, engagement, and page traffic at a glance.",
      "sections": {
        "profile": "Profile Summary",
        "stats": "Statistics Overview",
        "analytics": "Analytics",
        "messages": "Contact Messages"
      },
      "sectionError": "This section could not be loaded. Reload the page to try again."
    },
    "contactGallery": {
      "title": "Recent Inquiries",
      "description": "Direct messages from your portfolio contact form.",
      "messageCount": "{count, plural, =1 {1 Message} other {# Messages}}",
      "searchPlaceholder": "Search messages...",
      "noMessages": "No messages found",
      "noSubject": "No Subject",
      "clickMore": "Click to read more",
      "subjectLabel": "Subject",
      "messageLabel": "Message",
      "noSubjectProvided": "No subject provided",
      "close": "Close",
      "clearSearch": "Clear search",
      "readMessageFrom": "Read the message from {name}"
    },
    "blog": {
      "title": "Blog Posts",
      "description": "Create and manage your articles, drafts, and published content.",
      "createButton": "New Blog",
      "emptyTitle": "No blogs found",
      "emptyDescription": "Create your first blog.",
      "deleteTitle": "Delete Blog?",
      "deleteDescription": "This action cannot be undone.",
      "loadError": "Failed to load this post.",
      "dialog": {
        "editTitle": "Edit blog",
        "createTitle": "Create blog",
        "editDescription": "Update the post and its translations, then save.",
        "createDescription": "Write the post, add translations, and publish when ready.",
        "retry": "Retry",
        "loadingLabel": "Loading blog",
        "cancelButton": "Cancel",
        "saveButton": "Save changes",
        "createSubmitButton": "Create post"
      },
      "toast": {
        "created": "Blog created",
        "updated": "Blog updated",
        "deleted": "Blog deleted",
        "saveError": "Failed to save blog",
        "deleteError": "Could not delete blog"
      },
      "form": {
        "draftFound": "Unsaved draft from {time} found.",
        "restore": "Restore",
        "discard": "Discard",
        "contentTranslationsTitle": "Content Translations",
        "titleLabel": "Title",
        "titlePlaceholder": "Post title...",
        "descriptionLabel": "Short Description",
        "descriptionPlaceholder": "Brief summary of the post...",
        "bodyLabel": "Body Content",
        "savePost": "Save Post"
      },
      "meta": {
        "slugLabel": "Slug",
        "slugPlaceholder": "my-awesome-blog",
        "projectLabel": "Related Project",
        "projectPlaceholder": "Select a project (optional)",
        "projectNone": "None",
        "publishedLabel": "Published",
        "coverImageLabel": "Cover Image",
        "tagsLabel": "Tags",
        "tagsPlaceholder": "Select tags..."
      },
      "overview": {
        "viewsChartTitle": "Views — last 30 days",
        "noViewsYet": "No views yet",
        "topPostsTitle": "Top posts",
        "dayViewsLabel": "{date}: {count, plural, =0 {No views} one {# view} other {# views}}",
        "topBlogViewsLabel": "{title}: {count, plural, =0 {No views} one {# view} other {# views}}",
        "likesLabel": "Likes",
        "clapsLabel": "Claps",
        "blogViewsLabel": "Blog Views",
        "allTimeSub": "All time",
        "last30DaysSub": "{count, number} in last 30 days"
      }
    },
    "comment": {
      "title": "Comments",
      "description": "Moderate comments left on your blogs and projects",
      "emptyTitle": "No comments yet",
      "emptyDescription": "Comments on your blogs and projects will show up here.",
      "avatarFallbackAlt": "User",
      "source": {
        "blog": "Blog: {title}",
        "project": "Project: {title}",
        "untitledProject": "Untitled",
        "unknown": "Unknown source"
      },
      "status": {
        "hidden": "Hidden"
      },
      "actions": {
        "restore": "Restore",
        "hide": "Hide"
      },
      "toast": {
        "hidden": "Comment hidden",
        "restored": "Comment restored",
        "updateError": "Error updating comment"
      },
      "dialog": {
        "hideTitle": "Hide Comment",
        "hideDescription": "This comment will no longer be visible to visitors. You can restore it later."
      }
    },
    "common": {
      "nav": {
        "soonBadge": "Soon"
      },
      "stats": {
        "messagesLabel": "Messages",
        "messagesSub": "{count, number} new",
        "projectsLabel": "Projects",
        "projectsSub": "Live works",
        "blogsLabel": "Blogs",
        "blogsSub": "Articles",
        "educationLabel": "Education",
        "educationSub": "Certificates",
        "companiesLabel": "Companies",
        "techStackLabel": "Tech Stack",
        "tagsLabel": "Tags"
      }
    },
    "company": {
      "title": "Work Experience",
      "description": "Maintain your professional timeline and company records",
      "createButton": "Add Experience",
      "emptyTitle": "No work experience",
      "emptyDescription": "Start by adding the first company you worked with.",
      "emptyAction": "Add Your First Entry",
      "present": "Present",
      "rolesBadge": "{count, plural, =1 {# Role} other {# Roles}}",
      "techStackBadge": "{count, number} Tech",
      "editLabel": "Edit {name}",
      "deleteLabel": "Delete {name}",
      "deleteTitle": "Delete work experience?",
      "deleteDescription": "Are you sure you want to delete <name></name> and all of its roles?",
      "toast": {
        "created": "Work experience created",
        "updated": "Work experience updated",
        "deleted": "Work experience deleted",
        "saveError": "Failed to save work experience",
        "deleteError": "Could not delete work experience"
      },
      "dialog": {
        "createTitle": "Add Work Experience",
        "editTitle": "Edit Work Experience",
        "createDescription": "Record a company, the dates you were there, and the roles you held.",
        "editDescription": "Update this company, its dates, and the roles listed under it.",
        "logoLabel": "Company Logo",
        "companyLabel": "Company Name",
        "locationLabel": "Location",
        "startDateLabel": "Start Date",
        "endDateLabel": "End Date",
        "techStackLabel": "Tech Stack",
        "techStackPlaceholder": "Select tech stack",
        "techStackLoading": "Loading tech stacks…",
        "techStackError": "Tech stacks could not be loaded.",
        "translationsTitle": "Translations",
        "descriptionLabel": "Description",
        "rolesTitle": "Roles",
        "addRoleButton": "Add Role",
        "saveButton": "Save"
      },
      "role": {
        "fallbackTitle": "Role {index, number}",
        "removeButton": "Remove role",
        "removeConfirmTitle": "Remove this role?",
        "removeConfirmDescription": "{name}, together with its tasks and translations, will be removed from this form. Nothing is saved until you save the work experience.",
        "startDateLabel": "Start Date",
        "endDateLabel": "End Date",
        "titleLabel": "Role Title",
        "descriptionLabel": "Description",
        "tasksTitle": "Tasks",
        "addTaskButton": "Add Task"
      },
      "task": {
        "sortLabel": "Sort",
        "contentLabel": "Task",
        "removeButton": "Remove task"
      }
    },
    "education": {
      "title": "Education",
      "description": "Manage your academic background",
      "createButton": "Add Education",
      "emptyTitle": "No education entries",
      "emptyDescription": "Start by adding your first academic achievement.",
      "emptyAction": "Add Your First Entry",
      "untitled": "Untitled Education",
      "present": "Present",
      "ongoing": "Ongoing",
      "achievementCount": "{count, plural, =1 {1 Achievement} other {# Achievements}}",
      "editLabel": "Edit {name}",
      "deleteLabel": "Delete {name}",
      "deleteTitle": "Delete education?",
      "deleteDescription": "Are you sure you want to delete <name></name>?",
      "toast": {
        "created": "Education created",
        "updated": "Education updated",
        "deleted": "Education deleted",
        "saveError": "Failed to save education",
        "deleteError": "Could not delete education"
      },
      "dialog": {
        "createTitle": "Add education",
        "editTitle": "Edit education",
        "createDescription": "Add a school or degree, then list what you achieved there.",
        "editDescription": "Update this entry and the achievements listed under it.",
        "logoLabel": "Institution Logo",
        "startDateLabel": "Start Date",
        "endDateLabel": "End Date",
        "translationsTitle": "Translations",
        "translationsDescription": "One tab per language. Visitors see the tab matching their locale.",
        "schoolLabel": "School / Degree",
        "descriptionLabel": "Description",
        "descriptionPlaceholder": "A short summary of this program…",
        "cancelButton": "Cancel",
        "saveButton": "Save changes",
        "createSubmitButton": "Add education"
      },
      "achievements": {
        "title": "Achievements",
        "reorderHint": "Drag the handle to reorder — this is the order visitors see.",
        "addButton": "Add",
        "emptyText": "No achievements yet.",
        "addFirstButton": "Add the first one",
        "untitled": "Untitled achievement",
        "reorderAriaLabel": "Reorder achievement {index, number} of {total, number}",
        "removeAriaLabel": "Remove achievement",
        "removeConfirmTitle": "Remove this achievement?",
        "removeConfirmDescription": "{name}, together with everything typed into it, will be removed from this form. Nothing is saved until you save the education entry.",
        "imagesLabel": "Images",
        "titleLabel": "Title",
        "contentLabel": "Content",
        "contentPlaceholder": "Describe this achievement…"
      }
    },
    "media": {
      "title": "Media Library",
      "description": "Centralized storage for your portfolio assets and banner images.",
      "addButton": "Add Media",
      "empty": {
        "title": "No media found",
        "description": "Your library is empty. Upload your first image to get started."
      },
      "dialog": {
        "uploadTitle": "Upload Media",
        "deleteTitle": "Delete Media",
        "deleteDescription": "This will permanently delete this media file. This action cannot be undone."
      },
      "picker": {
        "libraryLabel": "Library",
        "uploadButton": "Upload",
        "uploadAssetsTitle": "Upload Assets",
        "clearAll": "Clear All",
        "selectMedia": "Select Media",
        "selectedCount": "{count, plural, =1 {1 selected} other {# selected}}",
        "moreCount": "{count, plural, =1 {+ 1 more} other {+ # more}}",
        "clickToManage": "Click to manage",
        "clickToChange": "Click to change",
        "chooseFromLibrary": "Upload or choose from library",
        "selectedAlt": "Selected",
        "loadMore": "Load More"
      },
      "upload": {
        "dropzoneText": "Click or drag images here",
        "invalidTypeTitle": "Invalid type",
        "invalidTypeDescription": "{fileName} is not an image.",
        "fileTooLargeTitle": "File too large",
        "fileTooLargeDescription": "{fileName} exceeds {maxSize, number}MB.",
        "successTitle": "Success",
        "successDescription": "All images uploaded.",
        "uploadFailedTitle": "Upload failed",
        "uploadButton": "{count, plural, =1 {Upload 1 File} other {Upload # Files}}"
      },
      "toast": {
        "uploadSuccess": "Upload successful",
        "uploadError": "Upload failed",
        "deleteSuccess": "Media deleted",
        "deleteError": "Could not delete media"
      }
    },
    "health": {
      "title": "Health",
      "loading": "Loading health data…",
      "tabs": {
        "overview": "Overview",
        "sleep": "Sleep",
        "gym": "Gym"
      },
      "units": {
        "hoursMinutes": "{hours, number}h {minutes, number}m",
        "minutes": "{minutes, number}m"
      },
      "hub": {
        "ariaLabel": "Sleep statistics",
        "lastNight": "Last night",
        "debt": "Sleep debt",
        "streak": "Streak",
        "noData": "No sleep logged yet",
        "logSleep": "Log sleep",
        "editSleep": "Update last night",
        "estimated": "Estimated"
      },
      "sleep": {
        "title": "Sleep",
        "bedAt": "Bedtime",
        "wakeAt": "Wake time",
        "duration": "Duration",
        "quality": "Quality",
        "qualityValue": "Quality {value, number} of 5",
        "qualityClear": "No quality rating",
        "factors": "Factors",
        "freeDay": "Free day today",
        "latency": "Time to fall asleep",
        "awakenings": "Minutes awake",
        "note": "Note",
        "save": "Save",
        "saving": "Saving…",
        "saved": "Sleep saved",
        "statsAriaLabel": "Sleep statistics",
        "efficiency": "Efficiency",
        "bedtimeSd": "Bedtime variation",
        "waketimeSd": "Wake variation",
        "debt": "Sleep debt",
        "streak": "Streak",
        "durationChart": "Sleep duration, last 14 days",
        "durationSummary": "Nightly sleep duration in hours for the last 14 days",
        "efficiencyUnavailable": "Add time to fall asleep or minutes awake to see efficiency",
        "debtCaveat": "A rolling 14-day heuristic, not a clinical measure",
        "noHistory": "Nothing logged yet — save your first night above.",
        "regularity": "Regularity",
        "sri": "Regularity index (SRI)",
        "sriCaveat": "Computed from typed times, so it reads higher than a wearable would: it cannot see naps, and it does not know when your minutes awake fell. The two variation figures below assume none of that.",
        "socialJetlag": "Social jetlag",
        "socialJetlagHint": "How far your midsleep moves between work days and free days",
        "chronotype": "Chronotype (MSFsc)",
        "chronotypeHint": "Free-day midsleep, corrected for catch-up sleep. A clock time, not a length.",
        "noNightsLogged": "Nothing logged in the last 14 days.",
        "sriUnavailable": "Needs four nights in a row. {n, number} logged in the last 14 days.",
        "sdUnavailable": "Needs two nights in the last 14 days.",
        "socialJetlagUnavailable": "Needs three free days and three work days. So far: {free, number} free, {work, number} work.",
        "chronotypeUnavailable": "Needs three free days and three work days. So far: {free, number} free, {work, number} work.",
        "nightlyTarget": "Nightly target {hours, number}h {minutes, number}m",
        "overTarget": "{hours, number}h {minutes, number}m over target",
        "underTarget": "{hours, number}h {minutes, number}m short of target",
        "onTarget": "On target",
        "durationPending": "Enter both times",
        "qualityLevel1": "Poor",
        "qualityLevel2": "Restless",
        "qualityLevel3": "Fair",
        "qualityLevel4": "Good",
        "qualityLevel5": "Great",
        "qualityNone": "Not rated yet",
        "details": "Details",
        "detailsSummary": "Time to fall asleep, minutes awake, factors, note",
        "detailsEfficiencyHint": "Time to fall asleep and minutes awake are what make efficiency computable.",
        "detailsFilled": "{n, number} filled",
        "efficiencyContext": "Of the time you spent in bed",
        "streakContext": "{n, number} of the last {total, number} nights logged",
        "today": "Today",
        "calendar": "Nights in {month}",
        "calendarSummary": "Every night this month, by how long you slept",
        "calendarMissed": "Not logged",
        "calendarShorter": "Shorter",
        "calendarLonger": "Longer",
        "detailsDone": "Done"
      },
      "muscles": {
        "chest": "Chest",
        "back": "Back",
        "lats": "Lats",
        "traps": "Traps",
        "front_delts": "Front delts",
        "side_delts": "Side delts",
        "rear_delts": "Rear delts",
        "biceps": "Biceps",
        "triceps": "Triceps",
        "forearms": "Forearms",
        "quads": "Quads",
        "hamstrings": "Hamstrings",
        "glutes": "Glutes",
        "calves": "Calves",
        "core": "Core",
        "adductors": "Adductors",
        "abductors": "Abductors"
      },
      "equipment": {
        "barbell": "Barbell",
        "dumbbell": "Dumbbell",
        "machine": "Machine",
        "cable": "Cable",
        "bodyweight": "Bodyweight",
        "kettlebell": "Kettlebell",
        "band": "Band"
      },
      "metrics": {
        "weight_reps": "Weight × reps",
        "bodyweight_reps": "Bodyweight reps",
        "weighted_bodyweight": "Bodyweight + added weight",
        "time": "Time"
      },
      "gym": {
        "title": "Gym",
        "ariaLabel": "Gym",
        "start": "Start a workout",
        "startAction": "Start workout",
        "starting": "Starting…",
        "chooseRoutine": "Pick a routine",
        "routineAriaLabel": "Routine to start from",
        "emptySession": "No routine",
        "emptySessionHint": "Start with nothing planned and add exercises as you go.",
        "sessionName": "Session name",
        "defaultTitle": "Workout",
        "noRoutines": "No routines yet — start without one, or build one first.",
        "routinesLink": "Routines",
        "catalogLink": "Exercises",
        "inProgress": "Workout in progress",
        "inProgressHint": "Only one workout runs at a time. Finish this one before starting another.",
        "resume": "Resume",
        "startedAt": "Started {time}",
        "exerciseCount": "{n, number} exercises",
        "setCount": "{n, number} sets",
        "history": "History",
        "historyAriaLabel": "Workout history",
        "noHistory": "No workouts logged yet.",
        "rangeAriaLabel": "How far back to read",
        "range30": "30 days",
        "range90": "90 days",
        "range365": "1 year",
        "open": "Open",
        "duration": "Duration",
        "sessionRpe": "Session RPE",
        "sessionCount": "{n, number} workouts",
        "loading": "Loading workouts…"
      },
      "workout": {
        "back": "Back to gym",
        "notFound": "This workout no longer exists.",
        "inProgressBadge": "In progress",
        "finishedAt": "Finished {time}",
        "addExercise": "Add exercise",
        "noExercises": "No exercises yet — add the first one.",
        "exerciseAdded": "Exercise added",
        "exerciseRemoved": "Exercise removed",
        "removeExercise": "Remove exercise",
        "moveUp": "Move up",
        "moveDown": "Move down",
        "reordered": "Order saved",
        "sets": "Sets",
        "noSets": "No sets yet.",
        "addSet": "Add set",
        "editSet": "Edit set",
        "setNumber": "Set {n, number}",
        "setSaved": "Set saved",
        "setDeleted": "Set deleted",
        "deleteSet": "Delete set",
        "warmup": "Warm-up set",
        "warmupShort": "Warm-up",
        "warmupHint": "Warm-up sets stay out of volume and personal bests.",
        "reps": "Reps",
        "weight": "Weight (kg)",
        "addedWeight": "Added weight (kg)",
        "durationSec": "Duration (seconds)",
        "rpe": "RPE",
        "rpeHint": "0 to 10, in half steps. Optional.",
        "save": "Save",
        "saving": "Saving…",
        "setWeightReps": "{weight, number} kg × {reps, number}",
        "setReps": "{reps, number} reps",
        "setAddedReps": "+{weight, number} kg × {reps, number}",
        "setTime": "{seconds, number}s",
        "setEmpty": "Nothing recorded",
        "setRpe": "RPE {value, number}",
        "finish": "Finish workout",
        "finishHint": "How hard was the session as a whole?",
        "finishAction": "Finish",
        "finished": "Workout finished",
        "notes": "Notes",
        "notesPlaceholder": "Anything worth remembering about this session",
        "sessionRpeNone": "Not rated yet",
        "sessionRpeClear": "No session RPE",
        "sessionRpeValue": "Session RPE {value, number} of 10",
        "rpeLevel0": "Rest",
        "rpeLevel1": "Very easy",
        "rpeLevel2": "Easy",
        "rpeLevel3": "Moderate",
        "rpeLevel4": "Somewhat hard",
        "rpeLevel5": "Hard",
        "rpeLevel6": "Quite hard",
        "rpeLevel7": "Very hard",
        "rpeLevel8": "Really hard",
        "rpeLevel9": "Almost maximal",
        "rpeLevel10": "Maximal",
        "deleteWorkout": "Delete workout",
        "deleteWorkoutTitle": "Delete this workout?",
        "deleteWorkoutHint": "Its exercises and every set in it go with it. This cannot be undone.",
        "deleted": "Workout deleted",
        "loading": "Loading workout…",
        "moveUpNamed": "Move {name} up",
        "moveDownNamed": "Move {name} down",
        "removeExerciseNamed": "Remove {name}",
        "addSetNamed": "Add a set to {name}",
        "cancel": "Cancel"
      },
      "exercises": {
        "title": "Exercises",
        "description": "Everything a routine or a workout can pick from.",
        "search": "Search exercises",
        "clearSearch": "Clear search",
        "allMuscles": "All",
        "filterAriaLabel": "Filter by muscle",
        "showArchived": "Show archived",
        "create": "New exercise",
        "createTitle": "New exercise",
        "editTitle": "Edit exercise",
        "edit": "Edit",
        "name": "Name",
        "namePlaceholder": "Barbell bench press",
        "primaryMuscle": "Primary muscle",
        "secondaryMuscles": "Secondary muscles",
        "secondaryHint": "Optional. The muscle filter does not read these.",
        "equipment": "Equipment",
        "metric": "What a set records",
        "save": "Save",
        "saving": "Saving…",
        "created": "Exercise added",
        "updated": "Exercise updated",
        "archive": "Archive",
        "restore": "Restore",
        "archived": "Archived",
        "archivedToast": "Exercise archived",
        "restoredToast": "Exercise restored",
        "archiveHint": "Archiving only takes it out of the pickers. Nothing is deleted, so past workouts keep resolving.",
        "empty": "No exercises match.",
        "emptyAll": "Your catalogue is empty.",
        "count": "{n, number} exercises",
        "pickTitle": "Choose an exercise",
        "nameRequired": "A name is required.",
        "loading": "Loading exercises…",
        "noSecondary": "None",
        "editNamed": "Edit {name}",
        "archiveNamed": "Archive {name}",
        "restoreNamed": "Restore {name}"
      },
      "routines": {
        "title": "Routines",
        "description": "A plan a workout can start from.",
        "create": "New routine",
        "createTitle": "New routine",
        "editTitle": "Edit routine",
        "edit": "Edit",
        "name": "Name",
        "namePlaceholder": "Push day",
        "notes": "Notes",
        "notesPlaceholder": "How this session is meant to run",
        "items": "Exercises",
        "addItem": "Add exercise",
        "noItems": "No exercises yet.",
        "targets": "Targets",
        "targetSets": "Sets",
        "targetRepsLow": "Reps from",
        "targetRepsHigh": "Reps to",
        "targetRpe": "RPE",
        "restSec": "Rest (seconds)",
        "summarySets": "{n, number} sets",
        "summaryReps": "{low, number}–{high, number} reps",
        "summaryRepsExact": "{n, number} reps",
        "summaryRpe": "RPE {value, number}",
        "summaryRest": "{n, number}s rest",
        "noTargets": "No targets set",
        "moveUp": "Move up",
        "moveDown": "Move down",
        "remove": "Remove",
        "save": "Save",
        "saving": "Saving…",
        "created": "Routine created",
        "updated": "Routine updated",
        "archive": "Archive",
        "restore": "Restore",
        "archived": "Archived",
        "archivedToast": "Routine archived",
        "restoredToast": "Routine restored",
        "archiveHint": "Archiving only takes it out of the picker. Past workouts keep their link to it.",
        "showArchived": "Show archived",
        "empty": "No routines yet.",
        "itemCount": "{n, number} exercises",
        "repsRangeError": "The lower rep target must not exceed the upper one.",
        "loading": "Loading routines…",
        "moreItems": "+{n, number} more",
        "editNamed": "Edit {name}",
        "archiveNamed": "Archive {name}",
        "restoreNamed": "Restore {name}",
        "moveUpNamed": "Move {name} up",
        "moveDownNamed": "Move {name} down",
        "removeNamed": "Remove {name}"
      },
      "factors": {
        "caffeine_late": "Late caffeine",
        "alcohol": "Alcohol",
        "screen_late": "Late screen",
        "late_meal": "Late meal",
        "workout_late": "Late workout",
        "ill": "Unwell"
      },
      "errors": {
        "load": "Could not load health data",
        "save": "Could not save"
      }
    },
    "note": {
      "title": "Notes",
      "description": "Your private notes. Nothing here is ever published.",
      "untitled": "Untitled",
      "untitledFolder": "New folder",
      "loading": "Loading note…",
      "emptySelection": "Select a note, or create one.",
      "folderNotEditable": "This is a folder — it has no document to edit.",
      "conflict": {
        "title": "This note changed somewhere else",
        "description": "Another device saved it {serverAt}. This browser still holds edits from {localAt} that never reached the server.",
        "keepMine": "Keep mine",
        "takeServer": "Use theirs"
      },
      "sync": {
        "recovered": "{count, plural, one {Recovered # unsaved note} other {Recovered # unsaved notes}}"
      },
      "backToList": "All notes",
      "tree": {
        "expandAriaLabel": "Expand",
        "collapseAriaLabel": "Collapse",
        "actionsAriaLabel": "Note actions",
        "treeAriaLabel": "Note tree",
        "draftNoteLabel": "New note name",
        "draftFolderLabel": "New folder name",
        "renameInputLabel": "Rename"
      },
      "fields": {
        "title": "Note title",
        "titlePlaceholder": "Untitled"
      },
      "actions": {
        "create": "New note",
        "newFolder": "New folder",
        "newNoteInside": "New note inside",
        "newFolderInside": "New folder inside",
        "rename": "Rename",
        "pin": "Pin",
        "unpin": "Unpin",
        "archive": "Archive",
        "restore": "Restore",
        "delete": "Delete",
        "deleteForever": "Delete permanently",
        "share": "Share",
        "showArchived": "Archived",
        "hideArchived": "Back to notes"
      },
      "status": {
        "saving": "Saving…",
        "saved": "Saved",
        "error": "Not saved",
        "retry": "Retry"
      },
      "view": {
        "label": "Editor view",
        "editor": "Editor",
        "markdown": "Markdown"
      },
      "markdown": {
        "format": "Clean up markdown",
        "formatted": "Markdown tidied up.",
        "alreadyClean": "Markdown is already tidy."
      },
      "relabel": {
        "prompt": "{count, plural, one {# note still shows the old name} other {# notes still show the old name}}.",
        "confirm": "Update labels",
        "done": "{count, plural, one {Updated # note} other {Updated # notes}}.",
        "failed": "Could not update link labels"
      },
      "properties": {
        "title": "Properties",
        "status": "Status",
        "statusPlaceholder": "e.g. draft",
        "presets": {
          "draft": "Draft",
          "active": "Active",
          "done": "Done"
        },
        "key": "Property name",
        "keyPlaceholder": "Name",
        "value": "Property value",
        "valuePlaceholder": "Value",
        "valueFor": "Value of {key}",
        "add": "Add property",
        "remove": "Remove {key}",
        "labels": "Labels",
        "labelsPlaceholder": "Add label…",
        "removeLabel": "Remove label {name}"
      },
      "cheatSheet": {
        "open": "Markdown help",
        "title": "Markdown cheat sheet",
        "description": "Type these as you write — they turn into formatting instantly.",
        "noSyntax": "Drag & drop / paste",
        "sections": {
          "basics": "Basics",
          "blocks": "Blocks",
          "linksMedia": "Links & media",
          "tables": "Tables",
          "math": "Math"
        },
        "rows": {
          "heading": "Heading — one # per level, then a space.",
          "bold": "Bold text.",
          "italic": "Italic text.",
          "strike": "Strikethrough.",
          "code": "Inline code.",
          "quote": "Blockquote — type > then a space.",
          "list": "Bulleted or numbered list.",
          "fence": "Code block — three backticks, optional language.",
          "rule": "Horizontal divider.",
          "noteLink": "Link to another note — type [[ and pick one.",
          "image": "Drop an image file or paste a screenshot to insert it.",
          "table": "Paste a markdown table and it becomes a real table.",
          "mathInline": "Inline math, rendered as you type.",
          "mathBlock": "Math block on its own line, in display style."
        }
      },
      "rename": {
        "title": "Rename",
        "label": "New name",
        "save": "Save",
        "cancel": "Cancel"
      },
      "sidebar": {
        "title": "Note panel",
        "toc": "Contents",
        "links": "Links",
        "files": "Files",
        "cite": "Cite",
        "tocEmpty": "Headings you add will show up here."
      },
      "explorer": {
        "viewMode": "View",
        "modes": {
          "tree": "Tree",
          "flat": "Flat list",
          "grouped": "Grouped"
        },
        "sortLabel": "Sort by",
        "sort": {
          "updated": "Last edited",
          "created": "Date created",
          "title": "Title"
        },
        "groupByLabel": "Group by",
        "groupBy": {
          "status": "Status",
          "label": "Label"
        },
        "noLabel": "No label",
        "dropToRoot": "Drop here to move to top level",
        "resizeAriaLabel": "Resize the note list",
        "collapseSidebar": "Hide note list",
        "expandSidebar": "Show note list",
        "breadcrumbAriaLabel": "Note location"
      },
      "search": {
        "trigger": "Search notes",
        "placeholder": "Search your notes…",
        "loading": "Searching…",
        "empty": "No notes match.",
        "actionsHeading": "Actions",
        "actionNewNote": "New note",
        "actionCheatSheet": "Markdown help"
      },
      "archive": {
        "title": "Archived",
        "empty": "Nothing archived."
      },
      "delete": {
        "title": "Delete permanently?",
        "description": "“{title}” will be deleted for good. This cannot be undone.",
        "descriptionWithChildren": "“{title}” and {count, plural, one {its # nested note} other {its # nested notes}} will be deleted for good. This cannot be undone.",
        "descriptionShared": "{count, plural, one {# person} other {# people}} can currently open this. Deleting it removes their access too.",
        "impactUnknown": "Could not check what this affects. It may take nested notes with it, and other people may lose access.",
        "confirm": "Delete permanently",
        "cancel": "Cancel"
      },
      "archiveConfirm": {
        "title": "Move “{title}” to the archive?",
        "description": "You can restore it from the Archived view.",
        "descriptionWithChildren": "{count, plural, one {Its # nested note} other {Its # nested notes}} will go with it. You can restore them from the Archived view.",
        "confirm": "Move to archive",
        "cancel": "Cancel"
      },
      "move": {
        "sharedTitle": "Move into a shared folder?",
        "sharedDescription": "“{title}” will become visible to {count, plural, one {# person} other {# people}} who can already open the destination.",
        "sharedConfirm": "Move anyway",
        "sharedCancel": "Cancel"
      },
      "share": {
        "title": "Share “{title}”",
        "descriptionNote": "People you invite can open this note only. Nothing else in your space becomes visible to them.",
        "descriptionFolder": "People you invite can open this folder and everything inside it — including notes you move in later.",
        "emailLabel": "Email address",
        "emailPlaceholder": "name@example.com",
        "roleViewer": "Can view",
        "roleEditor": "Can edit",
        "invite": "Invite",
        "pending": "Pending",
        "accepted": "Accepted",
        "revoke": "Remove access",
        "empty": "Not shared with anyone yet.",
        "loading": "Loading people…",
        "failed": "Could not load who has access.",
        "revokeFailed": "Access was not removed.",
        "roleFailed": "The role was not changed."
      },
      "links": {
        "title": "Links",
        "loading": "Loading links…",
        "outgoing": "Links out",
        "incoming": "Mentioned by",
        "empty": "No links yet.",
        "open": "Show links",
        "close": "Hide links",
        "deleted": "Deleted note",
        "expandAriaLabel": "Expand links",
        "collapseAriaLabel": "Collapse links",
        "insert": "Link to note",
        "pickerPlaceholder": "Link to a note…",
        "pickerEmpty": "No notes match.",
        "pickerCreate": "Create note “{title}”"
      },
      "attachments": {
        "title": "Files",
        "empty": "No files yet.",
        "dropHint": "Drop a PDF here to attach it.",
        "dropActive": "Drop to attach",
        "choose": "Add a PDF",
        "uploading": "Uploading…",
        "open": "Open",
        "openNewTab": "Open in a new tab",
        "download": "Download",
        "delete": "Remove",
        "deleteConfirm": "Remove for good",
        "deleteConfirmCancel": "Cancel",
        "close": "Close file",
        "prev": "Previous file",
        "next": "Next file",
        "viewerFallback": "Not showing? Open it in a new tab — some browsers, iOS Safari in particular, will not render a PDF in place.",
        "count": "{count, plural, =0 {No files} one {# file} other {# files}}",
        "sizeLabel": "{size} {unit}",
        "errors": {
          "type": "{fileName} is not a PDF.",
          "size": "{fileName} exceeds {maxSizeMb, number}MB.",
          "upload": "Could not attach the file.",
          "load": "Could not load the files."
        },
        "resizeAriaLabel": "Resize the reader"
      },
      "toasts": {
        "archived": "Moved to archive",
        "restored": "Note restored",
        "deleted": "Note deleted",
        "attachmentAdded": "File attached",
        "attachmentRemoved": "File removed",
        "attachmentIgnored": "{fileName} was not attached — only PDFs can be."
      },
      "empty": {
        "title": "No notes yet."
      },
      "errors": {
        "load": "Could not load your notes.",
        "create": "Could not create the note.",
        "save": "Could not save the note.",
        "archive": "Could not archive the note.",
        "restore": "Could not restore the note.",
        "delete": "Could not delete the note.",
        "links": "Could not load links.",
        "ancestors": "Could not load the note's location."
      },
      "graph": {
        "title": "Knowledge graph",
        "description": "Every note, and the links between them.",
        "empty": "No notes to plot yet — write a few and connect them with [[.",
        "loadError": "Couldn't load the graph. Reload to try again.",
        "legendHint": "Scroll to zoom, drag to pan, click a node to open it.",
        "resetView": "Reset the view",
        "nodeCount": "{count, plural, one {# note} other {# notes}}",
        "edgeCount": "{count, plural, one {# link} other {# links}}",
        "truncated": "Partial view — only the most recently updated notes are plotted.",
        "loading": "Loading knowledge graph…",
        "canvasLabel": "Knowledge graph, interactive",
        "keyboardHint": "Use the arrow keys to move between notes, Enter to open the focused note, and Escape to leave it.",
        "noteListLabel": "Every note in the graph:"
      },
      "views": {
        "label": "Note views",
        "list": "List",
        "graph": "Graph"
      },
      "export": {
        "label": "Export",
        "markdown": "Download .md",
        "pdf": "Print / Save as PDF",
        "notReady": "The note is still loading."
      }
    },
    "space": {
      "title": "Space",
      "navAriaLabel": "Workspace navigation",
      "openNav": "Open workspace navigation",
      "items": {
        "hub": "Overview",
        "notes": "Notes",
        "health": "Health"
      },
      "actions": {
        "dashboard": "Dashboard",
        "signOut": "Sign out"
      },
      "hub": {
        "greeting": "Welcome back, {name}",
        "subtitle": "Your private workspace",
        "stats": {
          "ariaLabel": "Workspace statistics",
          "notes": "Notes",
          "links": "Links between notes",
          "archived": "In trash"
        },
        "recent": {
          "title": "Recently edited",
          "empty": "Nothing here yet — create your first note.",
          "untitled": "Untitled"
        },
        "modules": {
          "notesTitle": "Notes",
          "notesDescription": "Interconnected notes with backlinks, math, markdown — and a graph view of how they all connect.",
          "healthTitle": "Health",
          "healthDescription": "Sleep, training, and the numbers that connect them."
        },
        "errors": {
          "load": "Couldn't load your workspace overview. Reload to try again."
        },
        "loading": "Loading workspace…"
      },
      "settings": {
        "title": "Workspace settings",
        "description": "How the notes workspace looks and behaves. Changes save on their own.",
        "open": "Settings",
        "openWithShortcut": "Settings (⌘,)",
        "saving": "Saving…",
        "saved": "Saved",
        "saveError": "Could not save",
        "closeWhileRunning": "A maintenance job is still running. Closing this stops it and discards the progress it has made.",
        "closeAnyway": "Close anyway",
        "groups": {
          "appearance": "Appearance",
          "editing": "Editing",
          "links": "Links",
          "maintenance": "Maintenance"
        },
        "appearance": {
          "density": {
            "label": "Density",
            "description": "How much space sits between paragraphs, headings and list items.",
            "options": {
              "comfortable": "Comfortable",
              "compact": "Compact"
            }
          },
          "typeScale": {
            "label": "Text size",
            "description": "Body size on the writing surface. Stays at 16px on phones — below that, iOS zooms the page whenever you tap into the editor.",
            "options": {
              "small": "Small",
              "medium": "Medium",
              "large": "Large"
            }
          },
          "readableLineLength": {
            "label": "Readable line length",
            "description": "Caps the writing column so a line stays short enough to read comfortably. Turn off to use the full width of the pane."
          }
        },
        "editing": {
          "autosaveSpeed": {
            "label": "Autosave delay",
            "description": "How long the editor waits after your last keystroke before saving. Your text is written to this browser immediately either way.",
            "options": {
              "fast": "Fast (0.4s)",
              "normal": "Normal (1s)",
              "relaxed": "Relaxed (2.5s)"
            }
          },
          "spellCheck": {
            "label": "Spell check",
            "description": "Let the browser underline words it does not recognise."
          },
          "formatOnExit": {
            "label": "Tidy markdown when leaving Markdown view",
            "description": "Runs the clean-up automatically when you switch back to the editor, instead of only when you press the button."
          },
          "formatOnPaste": {
            "label": "Tidy pasted markdown",
            "description": "Cleans up what you paste into the Markdown view. Only the pasted text is touched — never what you already wrote."
          }
        },
        "links": {
          "updateOnRename": {
            "label": "Update link labels on rename",
            "description": "When you rename a note, what should happen to links in other notes that still show its old name.",
            "options": {
              "always": "Always update",
              "ask": "Ask me",
              "never": "Never"
            },
            "note": "Only the visible text is ever changed, and only where it is still an exact copy of the old title — a label you wrote yourself is left alone. Links never break: they point at the note's id, not its name."
          }
        },
        "maintenance": {
          "intro": "Whole-vault jobs. Each runs in batches in the background, reports real progress, and can be stopped at any point — everything already processed stays processed.",
          "run": "Run",
          "cancel": "Stop",
          "progress": "{processed, number} of {total, number} notes",
          "cancelled": "Stopped after {processed, number} notes.",
          "failed": "Job failed",
          "confirmRun": "Yes, run it",
          "confirmDismiss": "Leave my notes alone",
          "jobs": {
            "pastedFormatting": {
              "title": "Clear formatting that came in from a paste",
              "description": "Rewrites every note, removing text colour, highlight colour, column widths copied from a source table, and link styling carried in from another page. Everything that means something is kept: tables, header rows, merged cells, lists, links and where they point, code blocks, headings, bold, italic and strikethrough.",
              "warning": "This cannot be undone. A colour you chose yourself is stored exactly like a colour that arrived with a paste, so this removes both, in every note. Nothing can tell them apart after the fact, and there is no way to put them back — export anything you care about first.",
              "result": "{count, plural, =0 {Examined {examined, number} notes. None of them was carrying pasted formatting.} one {Examined {examined, number} notes and rewrote #.} other {Examined {examined, number} notes and rewrote #.}}"
            },
            "staleLinks": {
              "title": "Find links showing an old name",
              "description": "Lists links whose label no longer matches the title of the note they point at. A report only — nothing is rewritten, because a label you wrote yourself is indistinguishable from one left behind by a rename.",
              "result": "{count, plural, =0 {No mismatched labels found.} one {# link shows a different name.} other {# links show a different name.}}",
              "row": "shows “{label}”, now “{title}”"
            },
            "linkGraph": {
              "title": "Rebuild the link graph",
              "description": "Recomputes which note links to which, from the documents themselves. What the Graph page and the Links panel read from.",
              "result": "{count, plural, =0 {Everything was already correct.} one {Repaired # note.} other {Repaired # notes.}}"
            },
            "searchIndex": {
              "title": "Rebuild the search index",
              "description": "Recomputes the plain-text copy of each note that search runs against. Only notes whose text actually differs are written, so this does not disturb the “recently updated” ordering.",
              "result": "{count, plural, =0 {Everything was already correct.} one {Repaired # note.} other {Repaired # notes.}}"
            }
          }
        }
      }
    },
    "project": {
      "title": "Projects",
      "description": "Manage your portfolio gallery, case studies, and deployment links.",
      "createButton": "New Project",
      "emptyTitle": "No projects found",
      "emptyDescription": "Create your first project to showcase your work.",
      "editLabel": "Edit {name}",
      "deleteLabel": "Delete {name}",
      "unknownTagLabel": "Untitled tag",
      "deleteTitle": "Delete Project?",
      "deleteDescription": "This action cannot be undone. This will permanently delete the project and remove its data from our servers.",
      "dialog": {
        "createTitle": "New Project",
        "editTitle": "Edit Project",
        "createDescription": "Describe the project, link it to your tech stack and tags, then write the content for each language.",
        "editDescription": "Update this project's links, dates and per-language content.",
        "slugLabel": "Slug",
        "slugPlaceholder": "my-awesome-project",
        "startDateLabel": "Start Date",
        "endDateLabel": "End Date",
        "githubLinkLabel": "GitHub Link",
        "githubLinkPlaceholder": "https://github.com/...",
        "liveLinkLabel": "Live Link",
        "liveLinkPlaceholder": "https://...",
        "publishedLabel": "Published",
        "techStackLabel": "Tech Stack",
        "techStackPlaceholder": "Select tech stack",
        "tagsLabel": "Tags",
        "tagsPlaceholder": "Select tags",
        "translationsLabel": "Content Translations",
        "titleLabel": "Title",
        "descriptionLabel": "Description",
        "descriptionPlaceholder": "What this project is, and what it does…",
        "saveButton": "Save Project",
        "savingButton": "Saving...",
        "cancelButton": "Cancel"
      },
      "coauthors": {
        "title": "Co-authors",
        "addButton": "Add Co-author",
        "nameLabel": "Name",
        "namePlaceholder": "Jane Doe",
        "emailLabel": "Email",
        "emailPlaceholder": "jane@example.com",
        "removeButton": "Remove co-author"
      },
      "card": {
        "noDescription": "No description available.",
        "githubLinkLabel": "Open the GitHub repository for {name} (opens in a new tab)",
        "liveLinkLabel": "Open the live site for {name} (opens in a new tab)"
      },
      "toast": {
        "created": "Project created",
        "updated": "Project updated",
        "deleted": "Project deleted",
        "saveError": "Failed to save project",
        "deleteError": "Could not delete project"
      }
    },
    "tag": {
      "title": "Tags",
      "description": "Create and manage custom taxonomies to categorize your content.",
      "createButton": "Create New Tag",
      "emptyTitle": "No tags found",
      "emptyDescription": "Create tags to organize your content library.",
      "emptyAction": "Create First Tag",
      "deleteTitle": "Delete Tag",
      "deleteDescription": "This will permanently delete the tag <name></name>. This action cannot be undone.",
      "dialog": {
        "createTitle": "Create Tag",
        "editTitle": "Edit Tag",
        "slugLabel": "Slug",
        "slugPlaceholder": "reactjs",
        "translationsLabel": "Translations",
        "addButton": "Add",
        "languageLabel": "Language",
        "languagePlaceholder": "en",
        "nameLabel": "Name",
        "namePlaceholder": "React",
        "cancelButton": "Cancel",
        "saveButton": "Save"
      },
      "toast": {
        "created": "Tag created",
        "updated": "Tag updated",
        "deleted": "Tag deleted",
        "saveError": "Failed to save tag",
        "deleteError": "Could not delete tag"
      }
    },
    "techStack": {
      "title": "Tech Stack",
      "description": "Maintain the list of technologies, frameworks, and tools you use.",
      "createButton": "Add TechStack",
      "emptyTitle": "No tech stacks found",
      "otherGroup": "Other",
      "editLabel": "Edit {name}",
      "deleteLabel": "Delete {name}",
      "deleteTitle": "Remove Tech stack",
      "deleteDescription": "Are you sure you want to remove <name></name>? This will hide it from your tech stack showcase.",
      "dialog": {
        "createTitle": "Add Tech Stack",
        "editTitle": "Edit Tech Stack",
        "createDescription": "Add a technology, its slug, and the group it belongs to.",
        "editDescription": "Update this technology's name, slug, group and logo.",
        "nameLabel": "Name",
        "slugLabel": "Slug",
        "groupLabel": "Group",
        "logoLabel": "Logo",
        "saveButton": "Save"
      },
      "toast": {
        "created": "Tech stack created",
        "updated": "Tech stack updated",
        "deleted": "Tech stack deleted",
        "saveError": "Failed to save tech stack",
        "deleteError": "Could not delete tech stack"
      }
    },
    "userProfile": {
      "title": "Profile Settings",
      "description": "Manage your global identity.",
      "resetButton": "Reset",
      "cancelButton": "Cancel",
      "saveButton": "Save",
      "reset": {
        "confirmTitle": "Discard unsaved changes?",
        "confirmDescription": "Every edit you have made, in every language, will be reverted to the last saved profile.",
        "confirmAction": "Discard changes"
      },
      "translations": {
        "heading": "Translations",
        "addLanguage": "Add Language",
        "newTabLabel": "NEW",
        "removeLanguageLabel": "Remove this language",
        "removeConfirmTitle": "Remove this language?",
        "removeConfirmDescription": "The {language} name, bio, quote and \"About me\" will be removed from this form. Nothing is saved until you save the profile.",
        "languageLabel": "Language",
        "languagePlaceholder": "en, vi..."
      },
      "commonInfo": {
        "heading": "Common Information",
        "description": "General profile settings",
        "birthdateLabel": "Birthdate"
      },
      "identity": {
        "sectionTitle": "Identity",
        "firstNameLabel": "First Name",
        "lastNameLabel": "Last Name",
        "displayNameLabel": "Display Name"
      },
      "content": {
        "sectionTitle": "Content",
        "greetingLabel": "Greeting",
        "taglineLabel": "Tagline",
        "taglinePlaceholder": "Hi, I'm...",
        "bioLabel": "Short Bio",
        "bioPlaceholder": "Fullstack developer..."
      },
      "quote": {
        "sectionTitle": "Quote",
        "quoteLabel": "Quote",
        "quotePlaceholder": "Enter an inspiring quote...",
        "authorLabel": "Author"
      },
      "aboutMe": {
        "sectionTitle": "About Me"
      },
      "socialLinks": {
        "heading": "Social Links",
        "description": "Add your social profiles",
        "addLink": "Add Link",
        "platformLabel": "Platform",
        "urlLabel": "URL",
        "removeLabel": "Remove this link",
        "unnamedLink": "this platform",
        "emptyTitle": "No social links yet",
        "emptyAction": "Add your first link",
        "platformPlaceholder": "GitHub",
        "urlPlaceholder": "https://...",
        "removeConfirm": "Remove this link?",
        "removeConfirmDescription": "The link to {platform} will be removed from this form. Nothing is saved until you save the profile."
      },
      "validation": {
        "platformRequired": "Platform is required",
        "urlInvalid": "Enter a full https:// address, or an email address",
        "languageRequired": "Language is required"
      },
      "toast": {
        "updated": "Profile updated",
        "saveError": "Save failed"
      }
    },
    "shared": {
      "translationTabs": {
        "addLanguage": "Add Language",
        "removeLanguage": "Remove Language",
        "languageLabel": "Language",
        "languagePlaceholder": "en, vi..."
      },
      "managerListState": {
        "loading": "Loading…",
        "errorTitle": "Something went wrong",
        "errorDescription": "The list could not be loaded. Please try again.",
        "retry": "Retry"
      },
      "confirmDelete": {
        "actionText": "Delete",
        "cancelText": "Cancel"
      },
      "pagination": {
        "pageLabel": "Page {page, number} of {totalPages, number}",
        "previous": "Previous",
        "next": "Next"
      },
      "actions": {
        "editItem": "Edit {name}",
        "deleteItem": "Delete {name}"
      }
    }
  },
  "auth": {
    "signInTitle": "Sign in to your account",
    "orContinueWith": "Or continue with",
    "signInWithGithub": "Continue with GitHub",
    "signInWithGoogle": "Continue with Google",
    "emailPlaceholder": "name@example.com",
    "sendMagicLink": "Send Magic Link",
    "accessDenied": "That account is not authorized to access this dashboard.",
    "signInFailed": "Sign in could not be completed. Please try again."
  },
  "share": {
    "invite": {
      "title": "Open a shared note",
      "description": "Sign in with the email address the note was shared with. A link sent to any other address will not open it.",
      "emailPlaceholder": "name@example.com",
      "submit": "Send me a link",
      "sent": "If that address has been invited, a sign-in link is on its way. Check your spam folder too.",
      "failed": "Something went wrong. Please try again.",
      "orContinueWith": "Or continue with"
    },
    "inbox": {
      "title": "Shared with you",
      "description": "Notes and folders other people have given you access to.",
      "empty": "Nothing has been shared with you yet.",
      "failed": "Could not load what has been shared with you.",
      "sharedBy": "Shared by {owner}",
      "roleViewer": "Can view",
      "roleEditor": "Can edit"
    },
    "note": {
      "notFound": "This note is no longer available.",
      "sharedWithYouLabel": "Shared with you",
      "breadcrumbAriaLabel": "Note path",
      "expand": "Expand",
      "collapse": "Collapse",
      "loading": "Loading…",
      "readOnly": "You have view-only access.",
      "backToInbox": "Shared with you",
      "saving": "Saving…",
      "saved": "Saved",
      "saveFailed": "Not saved",
      "retrySave": "Retry",
      "outOfScopeLink": "This link points outside what was shared with you.",
      "emptyFolder": "This folder is empty.",
      "selectNote": "Select a note.",
      "conflict": {
        "title": "This note changed while you were editing",
        "description": "Someone else saved it {serverAt}. Your changes from {localAt} have not been applied.",
        "keepMine": "Keep mine",
        "takeServer": "Use theirs"
      },
      "errors": {
        "save": "Could not save the note.",
        "conflict": "Your changes were not saved — someone else edited this note first."
      }
    }
  },
  "email": {
    "signIn": {
      "title": "Sign in to your account",
      "description": "Click the button below to access your dashboard.",
      "button": "Sign in",
      "expire": "This link will expire in 24 hours.",
      "ignore": "If you did not request this email, you can safely ignore it."
    },
    "sharedNote": {
      "subject": "{name} shared a note with you",
      "title": "A note has been shared with you",
      "description": "{owner} shared \"{title}\" with you. Sign in with this email address to open it.",
      "button": "Open the note",
      "ignore": "If you weren't expecting this, you can safely ignore this email."
    }
  }
};
export default messages;