import { cn } from "@/lib/utils"
import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight, Contact, CreditCard,
  Facebook,
  File,
  FileText, Fingerprint,
  FolderCog,
  Frown,
  Github,
  HelpCircle,
  Image,
  Languages,
  Laptop,
  Linkedin,
  Loader2, LucideProps, Mail, Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  type Icon as LucideIcon
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Fingerprint,
  close: X,
  spinner: Loader2,
  sad: Frown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  project: FolderCog,
  contact: Contact,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  github: Github,
  twitter: Twitter,
  linkedin: Linkedin,
  facebook: Facebook,
  email: Mail,
  check: Check,
  i18n: Languages,
  toc: ({ className, ...props }: LucideProps) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" className={cn("lucide lucide-table-of-contents-icon lucide-table-of-contents", className)} {...props}><path d="M16 12H3" /><path d="M16 18H3" /><path d="M16 6H3" /><path d="M21 12h.01" /><path d="M21 18h.01" /><path d="M21 6h.01" /></svg>
  ),
}
